# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

"""
FastAPI application for Sentinel Garden Environment v2.

Auto-generates HTTP/WebSocket endpoints via OpenEnv's create_app() factory.
Includes deep health checks and configurable concurrent environments.

Endpoints:
    POST /reset     — start episode, returns initial observation
    POST /step      — submit action, returns obs + reward
    GET  /state     — current episode state
    GET  /schema    — action/observation JSON schemas
    WS   /ws        — persistent WebSocket session
    GET  /health    — deep health check (model, data, judge)
    GET  /web       — interactive web UI (auto-generated by OpenEnv)
    GET  /docs      — OpenAPI/Swagger docs
"""

from __future__ import annotations

import argparse
import json
import logging
import os
import sys
from pathlib import Path

# Add project root to sys.path
ROOT = Path(__file__).resolve().parent.parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# OpenEnv imports with graceful fallback
# ---------------------------------------------------------------------------

try:
    from openenv.core.env_server.http_server import create_app as _create_openenv_app

    HAS_OPENENV = True
except ImportError:
    HAS_OPENENV = False
    _create_openenv_app = None  # type: ignore[assignment]
    logger.warning("openenv not installed; running in standalone mode")

from models import SentinelGardenAction, SentinelGardenObservation
from server.sentinel_garden_environment import SentinelGardenEnvironment

# ---------------------------------------------------------------------------
# FastAPI fallback for standalone mode
# ---------------------------------------------------------------------------

try:
    from fastapi import FastAPI, HTTPException, Request
    from fastapi.responses import JSONResponse

    HAS_FASTAPI = True
except ImportError:
    HAS_FASTAPI = False
    logger.warning("fastapi not installed")

# ---------------------------------------------------------------------------
# Config loading
# ---------------------------------------------------------------------------


def _load_config() -> dict:
    """Load configuration from config.yaml or environment variables."""
    config_path = os.getenv("SENTINEL_CONFIG", "config.yaml")
    if Path(config_path).exists():
        try:
            import yaml

            return yaml.safe_load(Path(config_path).read_text()) or {}
        except ImportError:
            logger.warning("PyYAML not installed, skipping config file")
        except Exception as exc:
            logger.warning("Failed to load config: %s", exc)
    return {}


# ---------------------------------------------------------------------------
# App factory
# ---------------------------------------------------------------------------


def create_standalone_app() -> "FastAPI":
    """Create a standalone FastAPI app when OpenEnv is not available."""
    app = FastAPI(
        title="Sentinel Garden Environment v2",
        description="RL environment for training LLM safety overseers",
        version="2.0.0",
    )

    # In-memory environment storage for concurrent episodes
    envs: dict[str, SentinelGardenEnvironment] = {}

    @app.post("/reset")
    async def reset(request: Request):
        body = await request.json()
        env_id = body.get("env_id", "default")
        task_type = body.get("task_type")

        config = _load_config()
        env = SentinelGardenEnvironment(config=config)
        envs[env_id] = env
        obs = env.reset(task_type=task_type)
        return JSONResponse({"observation": obs.model_dump(), "done": False})

    @app.post("/step")
    async def step(request: Request):
        body = await request.json()
        env_id = body.get("env_id", "default")
        action_data = body.get("action", {})

        env = envs.get(env_id)
        if env is None:
            raise HTTPException(status_code=404, detail="Environment not found")

        action = SentinelGardenAction(**action_data)
        obs = env.step(action)
        return JSONResponse(
            {
                "observation": obs.model_dump(),
                "reward": obs.reward,
                "done": obs.done,
            }
        )

    @app.get("/state")
    async def get_state(env_id: str = "default"):
        env = envs.get(env_id)
        if env is None:
            raise HTTPException(status_code=404, detail="Environment not found")
        return JSONResponse(env.state.model_dump())

    @app.get("/health")
    async def health():
        env = envs.get("default")
        if env:
            return JSONResponse(env.health_check())
        return JSONResponse({"status": "ok", "mode": "standalone"})

    @app.get("/schema")
    async def schema():
        return JSONResponse(
            {
                "action": SentinelGardenAction.model_json_schema(),
                "observation": SentinelGardenObservation.model_json_schema(),
            }
        )

    return app


def get_app():
    """Factory function that creates the appropriate app based on available dependencies."""
    config = _load_config()
    max_concurrent = config.get("environment", {}).get("max_concurrent_envs", 4)

    if HAS_OPENENV and _create_openenv_app is not None:
        logger.info("Creating OpenEnv-compatible app (max_concurrent=%d)", max_concurrent)
        return _create_openenv_app(
            SentinelGardenEnvironment,
            SentinelGardenAction,
            SentinelGardenObservation,
            env_name="sentinel_garden",
            max_concurrent_envs=max_concurrent,
        )
    elif HAS_FASTAPI:
        logger.info("Creating standalone FastAPI app")
        return create_standalone_app()
    else:
        raise RuntimeError(
            "Neither OpenEnv nor FastAPI is installed. "
            "Install dependencies: pip install openenv-core[core] fastapi uvicorn"
        )


# Create the app instance
app = get_app()


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------


def main():
    import uvicorn

    parser = argparse.ArgumentParser(description="Sentinel Garden Environment Server v2")
    parser.add_argument("--host", type=str, default="0.0.0.0")
    parser.add_argument("--port", type=int, default=8000)
    parser.add_argument("--workers", type=int, default=1)
    args, _ = parser.parse_known_args()

    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
    )

    logger.info(
        "Starting Sentinel Garden v2 on %s:%d (mode=%s, workers=%d)",
        args.host,
        args.port,
        "openenv" if HAS_OPENENV else "standalone",
        args.workers,
    )

    uvicorn.run(
        "server.app:app",
        host=args.host,
        port=args.port,
        workers=args.workers,
        log_level="info",
    )


if __name__ == "__main__":
    main()
